### ISSUE TITLE
Install react router

### ISSUE THREAD

**Issue by jsem** [CamHowling/DuneAtreides#1]
### Description
We need some sort of routing to handle transitioning between screens. React router used to be the standard so we will use this as a starting point.

### In Scope
- Install react router
- Define routes in routes.js for each screen
- Create a skeleton screen for each screen in the screens folder
- Modify App.js so that the router is displayed and the default screen is displayed on app startup

### Out of scope
- Speccing out the screens

### Definition of done
React router has been installed and a skeleton default screen is displayed on app startup

**Comment by CamHowling** [comment]
handled by nextjs.
