### ISSUE TITLE
Define colours

### ISSUE THREAD

**Issue by jsem** [CamHowling/DuneAtreides#2]
### Definition
We need to decide on a colour palette for the app

### In Scope
- Define colours to be used in the app
-- default text
-- default background
-- player name background for each faction
-- card type backgrounds for each card type
-- ...any more you can think of

### Definition of done
Colours are defined in colours.js

**Comment by CamHowling** [comment]
Current update: Sample colours from card title banners colour picked using aseprite for the following card types:
--Weapon
--Defense
--Worthless 
--Special (Note: this needs to be revised for higher green content)

	Weapon Cards
	
		#833031 Dark Red
		#A43831 Light Red
	
	Defense Cards
		
		#2E2A41 Dark Purple
		#3D3C5b Light Purple
		
	Worthless Cards
		
		#7E663A Dark Tan
		#AF986C Light Tan

	Special Cards
		
		#2d350f Dark Green


![Image](https://github.com/CamHowling/DuneAtreides/assets/15999072/3effbc24-ed8b-4cc4-9342-64bdbdd3df17)

Approximate font:
--Cooperplate Gothic Light (Capital letter larger)
--Qartella Heavy
--Paradigm Pro Bold
--Sylvia Bold

![gimp-2 10_sN1hfOfMWV](https://user-images.githubusercontent.com/15999072/149877965-7977566d-5890-491d-9e47-fb85fa115c88.png)

**Comment by CamHowling** [comment]
Faction Colours:

		#ca842a Fremen
		#49642b Atreides
		#222326 Harkonen
		#1b3366 Benegeserit
		#c3491e Spacing Guild
		#8a1d16 Emporer
		#2c1a48 Tleilaxu
		#7c7e82 Ixian


![Faction_Colours_Named](https://user-images.githubusercontent.com/15999072/149880894-742a8940-df04-41ac-8654-1a8778c02886.png)
![Faction_Colours_Codes_html](https://user-images.githubusercontent.com/15999072/149880898-91bc44f4-23dd-40c7-9337-5b73cf47f36b.png)

2nd Expansion Colours:

		#CD2515 Choam
		#CACCBF Richese Grey
		#292A30 Richese Blue

![Faction_Expansion2_Colours](https://user-images.githubusercontent.com/15999072/149911196-1558232a-1e8d-468b-8d25-87c0b4c64c91.png)

3rd Expansion Colours:

		#93348E Ecaz
		#3F95B4 Moritani

![Image](https://github.com/CamHowling/DuneAtreides/assets/15999072/7fef7fba-f260-4937-af4c-9cb070d86f70)

**Comment by CamHowling** [comment]
Background and Heading Colours:

		#171D29 Major Headings
		#20334D Minor Headings
		#FFFCF0 Main Background
		#E8D293 Footer Transition #1
		#B6A66C Footer Transition #1
		#3F1F19 Background Text
![Dune_BackgroundColours_Codes](https://user-images.githubusercontent.com/15999072/149883517-9fe5fbaf-7d3a-45aa-9673-e753a0676521.png)

**Comment by CamHowling** [comment]
Colour.js updated to include base + first expansion colours.

**Comment by CamHowling** [comment]
Unknown card banner swatches: Harkonen, Richese, Starting Hand

![dune_banner_unknown_swatch](https://user-images.githubusercontent.com/15999072/149912148-fa108545-edd6-42f8-8a8d-8477049c3d77.png)

replacements

![Image](https://github.com/CamHowling/DuneAtreides/assets/15999072/3575c85a-9de9-4a04-bdcc-1b362224ef76)

**Comment by CamHowling** [comment]
Expansion 2 colours updated in colour.js

Issue is ready for review.

**Comment by CamHowling** [comment]
Card banner previews, updated with new appearance:

![Image](https://github.com/CamHowling/DuneAtreides/assets/15999072/68af35f9-c2e0-434e-bc34-586b90355a74)

**Comment by jsem** [comment]
👍

**Comment by CamHowling** [comment]
Removed colours
~~#413429 Dark Brown~~
~~#73654A Light Brown~~
