### ISSUE TITLE
Spec out main screen

### ISSUE THREAD

**Issue by jsem** [CamHowling/DuneAtreides#3]
### Description
The default screen for the app is the main menu. Would be nice to spec this out so that we can see that the router and colours etc are working, as well as giving a solid starting point for speccing out the remaining screens.

### In Scope
- Setup main menu screen components

### Out of scope
- Making the screen functional

### Definition of Done
Main screen has been setup cosmetically

**Comment by CamHowling** [comment]
![Image](https://github.com/CamHowling/DuneAtreides/assets/15999072/e9cd617c-9b8e-41fe-b793-b4306c862109)

**Comment by CamHowling** [comment]
![Image](https://github.com/CamHowling/DuneAtreides/assets/15999072/6e97d1f2-befe-453a-ad8f-db1f82ee2e32)
